--- #YAML:1.0
name:                App-Repository
version:             0.966
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    App::Context:                  0
    App::Options:                  0
    DBI:                           0.01
    DBIx::Compat:                  0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
